# Generated by Django 2.0.2 on 2018-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
