# Generated by Django 2.0.2 on 2018-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='welcome_sub',
            field=models.CharField(default='hihi', max_length=50),
            preserve_default=False,
        ),
    ]
