# Generated by Django 2.0.2 on 2018-08-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_main_welcome_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(default='11', upload_to='main'),
            preserve_default=False,
        ),
    ]
