# Generated by Django 2.0.2 on 2018-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_main_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='logo',
            field=models.ImageField(default='logo.jpg', upload_to='main'),
            preserve_default=False,
        ),
    ]
