# Generated by Django 2.0.2 on 2018-08-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_main_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='tele',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='main',
            name='weibo',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(blank=True, default=None, upload_to='main'),
        ),
    ]
