# Generated by Django 2.0.2 on 2018-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_auto_20180828_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='address',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tele',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(default=' ', upload_to='main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='weibo',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
