# Generated by Django 2.0.2 on 2018-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_auto_20180828_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='address1',
        ),
        migrations.AddField(
            model_name='main',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tele',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(upload_to='main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='weibo',
            field=models.CharField(max_length=50),
        ),
    ]
