# Generated by Django 2.0.2 on 2018-08-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_auto_20180828_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='address',
        ),
    ]
