# Generated by Django 2.0.2 on 2018-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_remove_main_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='logo',
            field=models.ImageField(null=True, upload_to='main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='tele',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to='main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='weibo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
