# Generated by Django 2.0.2 on 2018-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_auto_20180828_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='tele',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='weibo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
