# Generated by Django 2.0.2 on 2018-08-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_auto_20180828_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='email',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tele',
        ),
        migrations.RemoveField(
            model_name='main',
            name='weibo',
        ),
        migrations.AlterField(
            model_name='main',
            name='logo',
            field=models.ImageField(default='', upload_to='main'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='wallpaper',
            field=models.ImageField(default='', upload_to='main'),
            preserve_default=False,
        ),
    ]
