# Generated by Django 2.0.2 on 2018-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0016_auto_20180828_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
