# Generated by Django 2.0.2 on 2018-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0017_auto_20180828_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='weibo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
