# Generated by Django 2.0.2 on 2018-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0018_auto_20180829_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='url',
        ),
        migrations.AddField(
            model_name='subsection',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='subsection'),
        ),
    ]
