# Generated by Django 2.0.2 on 2018-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0019_auto_20180830_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='block')),
            ],
        ),
    ]
