# Generated by Django 2.0.2 on 2018-08-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0021_auto_20180831_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='subname',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
