# Generated by Django 2.0.2 on 2018-08-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0022_subsection_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='subname',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
